### ISSUE TITLE
ResNet-151 features

### ISSUE THREAD

**Issue by fengfan028** [FloretCat/CMRAN#3]
hi~thanks for your work first!
The features in this repo are vgg19 features. Are there any features of resnet151？
If I extract the resnet151 features by myself, what are the video of noisy features?

**Comment by FloretCat** [comment]
Hi @fengfan028 ,

Thanks for your interest in our work!

You can find the resnet151 features [here.](https://github.com/FloretCat/CMRAN/issues/2#issuecomment-810058636)
We did not use the noisy videos when using resnet151 features in our experiments, since those videos were not released at that time. Now you can get the videos from [here.](https://github.com/YapengTian/AVE-ECCV18/issues/20#issuecomment-708133067)  

Thanks！

**Comment by fengfan028** [comment]
> 

thank you a lot~
